export enum TauriCommand {
  ToggleWindow = "toggle_window",
  ShowWindow = "show_window",
  GetWebviewVersion = "get_webview_version",
  HideDockIcon = "hide_dock_icon",
  ReadMarkdownFile = "read_markdown_file",
  WriteMarkdownFile = "write_markdown_file",
  StartShellTask = "start_shell_task",
  TakeScreenshot = "take_screenshot",
  ListFunASRModelBundles = "list_funasr_model_bundles",
  OpenFunASRModelsDir = "open_funasr_models_dir",
  PreloadFunASRModel = "preload_funasr_model",
  ShutdownNativeTranscript = "shutdown_native_transcript",
  StartNativeTranscript = "start_native_transcript",
  StopNativeTranscript = "stop_native_transcript",
}
